name: Build NTORS Rust APP Upload a Build Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure Git Credentials
      run: |
        git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@://github.com".insteadOf "https://://github.com"
    - name: Run tests
      run: cargo test --verbose
    - name: Build Linux
      run: cargo cross build --targets x86_64-unknown-linux-musl,aarch64-unknown-linux-musl --verbose --release
    - name: Build MacOS
      run: cargo cross build --target aarch64-apple-darwin --macos-sdk-version 11.0 --verbose --release
    - name: Build Windows
      run: cargo cross build --target x86_64-pc-windows-gnu --verbose --release

  upload:

    runs-on: ubuntu-latest

    steps:
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        # Artifact name. If the `archive` input is `false`, the name of the file uploaded will be the artifact name.
        name: # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload.
        path: ./target/release/NTORS.*
        # The desired behavior if no files are found using the provided path.
        include-hidden-files: true # optional, default is false
        # If true, the artifact will be archived (zipped) before uploading. If false, the artifact will be uploaded as-is without archiving. When `archive` is `false`, only a single file can be uploaded. The name of the file will be used as the artifact name (ignoring the `name` parameter).
        
